// All user-facing strings (pt-BR). Keep keys stable so other locales can be added.
export const S = {
  appName: 'Filezam',
  login: 'Entrar',
  username: 'Usuário',
  password: 'Senha',
  loginFailed: 'Usuário ou senha inválidos',
  loginLocked: 'Conta temporariamente bloqueada. Tente novamente mais tarde.',
  loginRateLimited: 'Muitas tentativas. Aguarde um pouco.',
  logout: 'Sair',
  changePassword: 'Alterar senha',
  mustChangePassword: 'Você precisa definir uma nova senha antes de continuar.',
  currentPassword: 'Senha atual',
  newPassword: 'Nova senha',
  confirmPassword: 'Confirmar nova senha',
  passwordMismatch: 'As senhas não conferem',
  passwordChanged: 'Senha alterada com sucesso',
  save: 'Salvar',
  cancel: 'Cancelar',
  close: 'Fechar',
  confirm: 'Confirmar',
  home: 'Início',
  favorites: 'Favoritos',
  shares: 'Compartilhamentos',
  uploads: 'Uploads',
  admin: 'Administração',
  users: 'Usuários',
  audit: 'Auditoria',
  name: 'Nome',
  size: 'Tamanho',
  modified: 'Modificado',
  type: 'Tipo',
  folder: 'Pasta',
  file: 'Arquivo',
  emptyFolder: 'Esta pasta está vazia',
  dropHere: 'Solte arquivos ou pastas aqui para enviar',
  newFolder: 'Nova pasta',
  newFolderName: 'Nome da nova pasta',
  uploadFiles: 'Enviar arquivos',
  uploadFolder: 'Enviar pasta',
  download: 'Baixar',
  downloadZip: 'Baixar como ZIP',
  copy: 'Copiar',
  cut: 'Recortar',
  paste: 'Colar',
  rename: 'Renomear',
  renameTo: 'Novo nome',
  delete: 'Excluir',
  deleteConfirm: (n: number) => (n === 1 ? 'Excluir 1 item permanentemente?' : `Excluir ${n} itens permanentemente?`),
  deleteWarning: 'Esta ação não pode ser desfeita.',
  share: 'Compartilhar',
  addFavorite: 'Adicionar aos favoritos',
  removeFavorite: 'Remover dos favoritos',
  open: 'Abrir',
  preview: 'Visualizar',
  selectAll: 'Selecionar tudo',
  selected: (n: number) => (n === 1 ? '1 item selecionado' : `${n} itens selecionados`),
  items: (n: number) => (n === 1 ? '1 item' : `${n} itens`),
  search: 'Filtrar nesta pasta',
  loading: 'Carregando…',
  error: 'Erro',
  retry: 'Tentar novamente',
  notFound: 'Não encontrado',
  conflictTitle: 'Já existe um item com este nome',
  conflictMessage: (name: string) => `"${name}" já existe no destino.`,
  overwrite: 'Substituir',
  skip: 'Pular',
  keepBoth: 'Manter ambos',
  applyToAll: 'Aplicar a todos',
  uploadPanelTitle: 'Uploads',
  uploadSpeed: 'velocidade',
  uploadRemaining: 'restante',
  pause: 'Pausar',
  resume: 'Retomar',
  cancelAll: 'Cancelar tudo',
  clearDone: 'Limpar concluídos',
  retryFailed: 'Repetir falhos',
  pendingUploads: (n: number) =>
    n === 1 ? '1 upload incompleto. Solte o mesmo arquivo aqui para retomar.' : `${n} uploads incompletos. Solte os mesmos arquivos aqui para retomar.`,
  discardPending: 'Descartar',
  noSpace: 'Sem espaço em disco no servidor',
  jobCopy: 'Copiando',
  jobMove: 'Movendo',
  jobDelete: 'Excluindo',
  jobDone: 'Concluído',
  jobFailed: 'Falhou',
  jobCancelled: 'Cancelado',
  shareTitle: 'Compartilhar pasta',
  shareExpires: 'Válido por',
  shareCreated: 'Link criado e copiado. Você pode copiá-lo de novo em Compartilhados.',
  shareLink: 'Link público',
  copyLink: 'Copiar link',
  shareCreatedCopied: 'Link criado e copiado',
  copyFailed: 'Não foi possível copiar. Selecione o texto e copie manualmente.',
  shareLinkGone: 'Link criado em uma versão anterior: só é possível copiá-lo criando um novo compartilhamento.',
  copied: 'Copiado!',
  shareRevoke: 'Revogar',
  shareRevokeConfirm: 'Revogar este link? Quem tiver o link perderá o acesso imediatamente.',
  shareExpired: 'Expirado',
  shareExpiresAt: 'Expira em',
  shareAccessCount: 'Acessos',
  shareNone: 'Nenhum compartilhamento ativo.',
  shareMoveWarning: 'Mover ou renomear a pasta invalida o link.',
  shareReadOnly: 'Somente leitura',
  publicNotFound: 'Este link não existe, expirou ou foi revogado.',
  hour: 'hora',
  hours: 'horas',
  day: 'dia',
  days: 'dias',
  userNew: 'Novo usuário',
  userEdit: 'Editar usuário',
  role: 'Perfil',
  roleAdmin: 'Administrador',
  roleUser: 'Usuário',
  scope: 'Pasta de acesso',
  scopeRoot: 'Raiz (tudo)',
  scopePick: 'Escolher pasta',
  scopeUse: 'Usar esta pasta',
  scopeHint: 'Navegue até a pasta desejada: a pasta em que você estiver será a pasta de acesso do usuário.',
  disabled: 'Desativado',
  forcePasswordChange: 'Exigir troca de senha no próximo login',
  resetPassword: 'Definir nova senha',
  userDeleteConfirm: (u: string) => `Excluir o usuário "${u}"? Favoritos e links dele serão removidos.`,
  created: 'Criado em',
  locked: 'Bloqueado até',
  actions: 'Ações',
  when: 'Quando',
  action: 'Ação',
  ip: 'IP',
  details: 'Detalhes',
  loadMore: 'Carregar mais',
  goUp: 'Subir um nível',
  refresh: 'Atualizar',
  view: 'Visualização',
  viewList: 'Lista',
  viewGrid: 'Grade',
  sortBy: 'Ordenar por',
  showHidden: 'Mostrar ocultos',
  settings: 'Configurações',
  prefShowHidden: 'Mostrar arquivos ocultos (nomes iniciados por ponto)',
  prefShowHints: 'Mostrar dicas de atalhos no rodapé',
  prefConfirmDelete: 'Pedir confirmação antes de excluir',
  properties: 'Propriedades',
  path: 'Caminho',
  copyPath: 'Copiar caminho',
  contents: 'Conteúdo',
  filesCount: (n: number) => (n === 1 ? '1 arquivo' : `${n} arquivos`),
  dirsCount: (n: number) => (n === 1 ? '1 pasta' : `${n} pastas`),
  partialCount: 'contagem parcial (pasta muito grande)',
  calculating: 'Calculando…',
  disk: 'Disco',
  diskFree: (free: string, total: string) => `${free} livres de ${total}`,
  sharesOfFolder: 'Links desta pasta',
  noSharesOfFolder: 'Nenhum link ativo para esta pasta.',
  lastAccess: 'Último acesso',
  expires: 'Expira',
  never: 'nunca',
  inFavorites: 'Está nos favoritos',
  symlink: 'Link simbólico',
  keyboardHint: 'Atalhos: Ctrl+C/X/V copiar/recortar/colar · F2 renomear · Del excluir · Enter abrir · Backspace subir · Ctrl+A tudo',
  errorCodes: {
    exists: 'Já existe um item com este nome',
    not_found: 'Item não encontrado',
    invalid_path: 'Caminho inválido',
    invalid_name: 'Nome inválido',
    no_space: 'Sem espaço em disco no servidor',
    nested: 'Não é possível mover/copiar uma pasta para dentro dela mesma',
    root_op: 'Operação não permitida na pasta raiz',
    is_dir: 'O destino é uma pasta',
    not_dir: 'O destino não é uma pasta',
    forbidden: 'Sem permissão',
    unauthorized: 'Sessão expirada. Entre novamente.',
    csrf: 'Requisição rejeitada por segurança',
    rate_limited: 'Muitas requisições. Aguarde um pouco.',
    busy: 'Servidor ocupado. Tentando novamente…',
    too_large: 'Arquivo grande demais para este modo de envio',
    weak_password: 'Senha fraca: use pelo menos 8 caracteres',
    bad_credentials: 'Credenciais inválidas',
    last_admin: 'Não é possível remover o último administrador',
    scope_unavailable: 'Sua pasta não está disponível. Contate o administrador.',
    fs_permission: 'Permissão negada no sistema de arquivos',
    upload_in_progress: 'Já existe um envio em andamento para este arquivo',
    internal: 'Erro interno no servidor',
    network: 'Falha de rede',
  } as Record<string, string>,
}

export function errorMessage(code: string | undefined, fallback?: string): string {
  return (code && S.errorCodes[code]) || fallback || S.errorCodes.internal
}
